version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:sdk
    steps:
      - checkout

      - run:
          name: Build the projects
          command: |
            cd src/tools/SoloX.ActionDispatch.Tools
            dotnet build -c Release
            cd ../../..

            dotnet build -c Release

      - run:
          name: Run Unit Tests
          command: |
            cd src/tests/SoloX.ActionDispatch.Core.UTest
            dotnet test -c Release --no-build
            cd ../../..

            cd src/tests/SoloX.ActionDispatch.Json.UTest
            dotnet test -c Release --no-build
            cd ../../..

            cd src/tests/SoloX.ActionDispatch.Core.ITest
            dotnet test -c Release --no-build
            cd ../../..

            cd src/tools.tests/SoloX.ActionDispatch.State.Generator.ITest
            dotnet test -c Release --no-build
            cd ../../..

      - run:
          name: Run Code coverage
          command: |
            dotnet tool install coveralls.net --version 1.0.0 --tool-path coveralls

            cd src/tests/SoloX.ActionDispatch.Core.UTest
            dotnet test -c Release --no-build -p:CollectCoverage=true -p:Exclude=\"[xunit.*]*,[SoloX.*.Sample*]*,[SoloX.*.UTest]*\" -p:MergeWith="../../../result.coverlet.json" -p:CoverletOutput="../../../result.coverlet.json"
            cd ../../..

            cd src/tests/SoloX.ActionDispatch.Json.UTest
            dotnet test -c Release --no-build -p:CollectCoverage=true -p:Exclude=\"[xunit.*]*,[SoloX.*.Sample*]*,[SoloX.*.UTest]*\" -p:MergeWith="../../../result.coverlet.json" -p:CoverletOutput="../../../result.coverlet.json"
            cd ../../..

            cd src/tests/SoloX.ActionDispatch.Core.ITest
            dotnet test -c Release --no-build -p:CollectCoverage=true -p:Exclude=\"[xunit.*]*,[SoloX.*.Sample*]*,[SoloX.*.ITest]*\" -p:MergeWith="../../../result.coverlet.json" -p:CoverletOutput="../../../result.coverlet.json"
            cd ../../..

            cd src/tools.tests/SoloX.ActionDispatch.State.Generator.ITest
            dotnet test -c Release --no-build -p:CollectCoverage=true -p:Exclude=\"[xunit.*]*,[SoloX.*.Sample*]*,[SoloX.*.ITest]*\" -p:MergeWith="../../../result.coverlet.json" -p:CoverletOutput="../../../result.opencover.xml" -p:CoverletOutputFormat="opencover"
            cd ../../..

            mkdir coverage
            cp result.opencover.xml coverage/result.opencover.xml
            coveralls/csmacnz.Coveralls --opencover -i coverage/result.opencover.xml --repoToken $COVERALLS_REPO_TOKEN --useRelativePaths --commitId $CIRCLE_SHA1 --commitBranch $CIRCLE_BRANCH --commitAuthor $CIRCLE_USERNAME --jobId $CIRCLE_BUILD_NUM --serviceName circleci

      - store_artifacts:
          path: coverage

      - run:
          name: Generate packages
          command: |
            mkdir packages

            cd src/libs/SoloX.ActionDispatch.Core
            dotnet pack -c Release --no-build
            cd ../../..
            mv src/libs/SoloX.ActionDispatch.Core/bin/Release/*.nupkg packages/

            cd src/libs/SoloX.ActionDispatch.Json
            dotnet pack -c Release --no-build
            cd ../../..
            mv src/libs/SoloX.ActionDispatch.Json/bin/Release/*.nupkg packages/

            cd src/tools/SoloX.ActionDispatch.Tools
            dotnet pack -c Release --no-build
            cd ../../..
            mv src/tools/SoloX.ActionDispatch.Tools/bin/Release/*.nupkg packages/

            cd src/tools/SoloX.ActionDispatch.State.Generator
            dotnet pack -c Release --no-build
            cd ../../..
            mv src/tools/SoloX.ActionDispatch.State.Generator/bin/Release/*.nupkg packages/

            cd src/tools/SoloX.ActionDispatch.State.Build
            dotnet pack -c Release --no-build
            cd ../../..
            mv src/tools/SoloX.ActionDispatch.State.Build/bin/Release/*.nupkg packages/

      - store_artifacts:
          path: packages